### ISSUE TITLE
Transparency also matters!

### ISSUE THREAD

**Issue by 1qh** [tenxsoydev/size-matters.nvim#12]
I would love to be able to adjust transparency of neovide (`vim.g.neovide_transparency`) with keyboard shortcuts. And I believe you can easily make an extension for that, or add that feature to this extension. 

I look forward to hearing from you!

Anyway, thanks a lot for this awesome extension!

**Comment by tobealive** [comment]
Hey @1qh,

thanks for reaching out. Sorry for taking so long with my response, it was a busy week!

Transparency also indeed does matter!

But this is  a "won't implement" for me. For two reasons. 

1.  It is a neovide only setting, and this plugin is more "general-use" - for GUI clients that support guifont.

2. The second reason is that it's already quite simple to change transparency. 
   
   - One way is to modify the variable, which becomes pretty simple if you use a wild-menu with auto completion.
   
   https://user-images.githubusercontent.com/34311583/219135115-cc7b77dd-c41e-40d9-82a3-65277068fc22.mov

   - If you want to have a keymap you can map a function containing something like:
   
   ```lua
   vim.g.neovide_transparency = vim.g.neovide_transparency - 0.05
   ```

**Comment by 1qh** [comment]
Thanks a lot!
